### ISSUE TITLE
Adding Uninstall windows apps

### ISSUE THREAD

**Issue by modz2014** [Fs00/Win10BloatRemover#10]
Hi maybe you can view a list of the windows apps Names before Uninstalling them

**Comment by Fs00** [comment]
Hi @modz2014! The app already displays the list of apps (or better, the app groups) that are going to be uninstalled.

![uwp_apps_list](https://user-images.githubusercontent.com/30041551/189721724-40d28f97-5c76-45aa-88f8-eb223fa656c0.png)

If I understand your request correctly, you'd like to also see the app package names (e.g. `Microsoft.Print3D`) in that list, correct?

**Comment by modz2014** [comment]
No that's fine what is said above is good but when I run it I don't see that

**Comment by modz2014** [comment]
I'm always thinking maybe a windows user interface with it of selected ones

**Comment by Fs00** [comment]
> when I run it I don't see that

What do you see exactly? Remember that the apps that are going to be uninstalled are specified [in the Configuration file](https://github.com/Fs00/Win10BloatRemover/blob/master/README.md#configuration).

> I'm always thinking maybe a windows user interface with it of selected ones

I have no plans to develop a GUI for the tool. Obviously a command-line interface is not as user-friendly, but it's much easier to maintain for me... it's a matter of trade-offs 🙂

**Comment by modz2014** [comment]
yer fair enough i might build something from it

**Comment by Fs00** [comment]
It should be pretty easy to put the features of the app behind a GUI, if you want. The [Operations](https://github.com/Fs00/Win10BloatRemover/tree/master/src/Operations) (which contain the logic) are already independent of the type of user interface, so you can use them as-is and develop the UI around them.

Since I've clarified your doubts (or at least I believe so!), I'm going to close this issue. Happy hacking!

**Comment by modz2014** [comment]
Yes that's fine I have a something in development for I will upload it to you and take a look
