### ISSUE TITLE
Feature Request - Disable and REMOVE useless services plus improvement

### ISSUE THREAD

**Issue by Felipefpl** [Fs00/Win10BloatRemover#13]
Hi, here is a suggestion to make your tool even better than it already is:

more services to disable and remove (they need to be removed for good to ensure they wont come back ;) )

https://www.youtube.com/watch?v=aIXDD4NKx60

If it's possible to add even more services to disable and remove please do it, every MB of RAM counts. ;) :+1: 

Another improvement would be an specific option to remove Windows Defender Anti-Virus (not the firewall), other debloaters have such option.

**Comment by Fs00** [comment]
Hi @Felipefpl,

> more services to disable and remove

You can add as many services to remove as you want in the configuration file, see the relevant section in the Readme for more details.
I have intentionally kept the default list to a minimum to avoid breaking some features of the OS.

> Another improvement would be an specific option to remove Windows Defender Anti-Virus

If I understand correctly, you'd like to completely remove the antivirus from the system instead of just disabling it? The tool used to do that in the past, but nowadays removing it permanently breaks installation of cumulative updates, which is something I don't want.

**Comment by Felipefpl** [comment]
Hi Fs00, thanks for the replies, i understand now the reasons why you kept things this way. I'll close the issue.
